<?xml version="1.0" encoding="utf-8"?>
<Database Name="Perbaffo" Class="ConfigurazioniDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.3\SQLEXPRESS;Initial Catalog=Perbaffo;Persist Security Info=True;User ID=Perbaffo" SettingsObjectName="Perbaffo.Presenter.Properties.Settings" SettingsPropertyName="PerbaffoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProdottiCategorie" Member="DettagliProdottiCategories">
    <Type Name="DettagliProdottiCategorie">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Notizie" Member="News">
    <Type Name="News">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UrlImmagine" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notizia" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Titolo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UrlFonte" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="DescrioneFonte" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Categorie" Member="Categories">
    <Type Name="Categorie">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescrizioneCategoria" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescrizioneBreve" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDCategoriaPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlImmagine" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescrizioneEstesa" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Errori" Member="Erroris">
    <Type Name="Errori">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescrException" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DescrStackTrace" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PathPagina" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DescrInnerException" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrentIDUtenteLoggato" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataErrore" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Browser" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Curiosita" Member="Curiositas">
    <Type Name="Curiosita">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DescrCuriosita" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>