#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perbaffo.Presenter.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Perbaffo")]
	public partial class ConfigurazioniDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDettagliProdottiCategorie(DettagliProdottiCategorie instance);
    partial void UpdateDettagliProdottiCategorie(DettagliProdottiCategorie instance);
    partial void DeleteDettagliProdottiCategorie(DettagliProdottiCategorie instance);
    partial void InsertNews(News instance);
    partial void UpdateNews(News instance);
    partial void DeleteNews(News instance);
    partial void InsertCategorie(Categorie instance);
    partial void UpdateCategorie(Categorie instance);
    partial void DeleteCategorie(Categorie instance);
    partial void InsertErrori(Errori instance);
    partial void UpdateErrori(Errori instance);
    partial void DeleteErrori(Errori instance);
    partial void InsertCuriosita(Curiosita instance);
    partial void UpdateCuriosita(Curiosita instance);
    partial void DeleteCuriosita(Curiosita instance);
    #endregion
		
		public ConfigurazioniDataContext() : 
				base(global::Perbaffo.Presenter.Properties.Settings.Default.PerbaffoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurazioniDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurazioniDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurazioniDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConfigurazioniDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DettagliProdottiCategorie> DettagliProdottiCategories
		{
			get
			{
				return this.GetTable<DettagliProdottiCategorie>();
			}
		}
		
		public System.Data.Linq.Table<News> News
		{
			get
			{
				return this.GetTable<News>();
			}
		}
		
		public System.Data.Linq.Table<Categorie> Categories
		{
			get
			{
				return this.GetTable<Categorie>();
			}
		}
		
		public System.Data.Linq.Table<Errori> Erroris
		{
			get
			{
				return this.GetTable<Errori>();
			}
		}
		
		public System.Data.Linq.Table<Curiosita> Curiositas
		{
			get
			{
				return this.GetTable<Curiosita>();
			}
		}
	}
	
	[Table(Name="dbo.ProdottiCategorie")]
	[DataContract()]
	public partial class DettagliProdottiCategorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDProdotto;
		
		private int _IDCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDProdottoChanging(int value);
    partial void OnIDProdottoChanged();
    partial void OnIDCategoriaChanging(int value);
    partial void OnIDCategoriaChanged();
    #endregion
		
		public DettagliProdottiCategorie()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_IDProdotto", DbType="Int NOT NULL")]
		[DataMember(Order=2)]
		public int IDProdotto
		{
			get
			{
				return this._IDProdotto;
			}
			set
			{
				if ((this._IDProdotto != value))
				{
					this.OnIDProdottoChanging(value);
					this.SendPropertyChanging();
					this._IDProdotto = value;
					this.SendPropertyChanged("IDProdotto");
					this.OnIDProdottoChanged();
				}
			}
		}
		
		[Column(Storage="_IDCategoria", DbType="Int NOT NULL")]
		[DataMember(Order=3)]
		public int IDCategoria
		{
			get
			{
				return this._IDCategoria;
			}
			set
			{
				if ((this._IDCategoria != value))
				{
					this.OnIDCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IDCategoria = value;
					this.SendPropertyChanged("IDCategoria");
					this.OnIDCategoriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.Notizie")]
	[DataContract()]
	public partial class News : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UrlImmagine;
		
		private string _Notizia;
		
		private System.DateTime _DataInserimento;
		
		private string _Titolo;
		
		private string _UrlFonte;
		
		private string _DescrioneFonte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUrlImmagineChanging(string value);
    partial void OnUrlImmagineChanged();
    partial void OnNotiziaChanging(string value);
    partial void OnNotiziaChanged();
    partial void OnDataInserimentoChanging(System.DateTime value);
    partial void OnDataInserimentoChanged();
    partial void OnTitoloChanging(string value);
    partial void OnTitoloChanged();
    partial void OnUrlFonteChanging(string value);
    partial void OnUrlFonteChanged();
    partial void OnDescrioneFonteChanging(string value);
    partial void OnDescrioneFonteChanged();
    #endregion
		
		public News()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_UrlImmagine", DbType="VarChar(50)")]
		[DataMember(Order=2)]
		public string UrlImmagine
		{
			get
			{
				return this._UrlImmagine;
			}
			set
			{
				if ((this._UrlImmagine != value))
				{
					this.OnUrlImmagineChanging(value);
					this.SendPropertyChanging();
					this._UrlImmagine = value;
					this.SendPropertyChanged("UrlImmagine");
					this.OnUrlImmagineChanged();
				}
			}
		}
		
		[Column(Storage="_Notizia", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[DataMember(Order=3)]
		public string Notizia
		{
			get
			{
				return this._Notizia;
			}
			set
			{
				if ((this._Notizia != value))
				{
					this.OnNotiziaChanging(value);
					this.SendPropertyChanging();
					this._Notizia = value;
					this.SendPropertyChanged("Notizia");
					this.OnNotiziaChanged();
				}
			}
		}
		
		[Column(Storage="_DataInserimento", DbType="DateTime NOT NULL")]
		[DataMember(Order=4)]
		public System.DateTime DataInserimento
		{
			get
			{
				return this._DataInserimento;
			}
			set
			{
				if ((this._DataInserimento != value))
				{
					this.OnDataInserimentoChanging(value);
					this.SendPropertyChanging();
					this._DataInserimento = value;
					this.SendPropertyChanged("DataInserimento");
					this.OnDataInserimentoChanged();
				}
			}
		}
		
		[Column(Storage="_Titolo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[DataMember(Order=5)]
		public string Titolo
		{
			get
			{
				return this._Titolo;
			}
			set
			{
				if ((this._Titolo != value))
				{
					this.OnTitoloChanging(value);
					this.SendPropertyChanging();
					this._Titolo = value;
					this.SendPropertyChanged("Titolo");
					this.OnTitoloChanged();
				}
			}
		}
		
		[Column(Storage="_UrlFonte", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		[DataMember(Order=6)]
		public string UrlFonte
		{
			get
			{
				return this._UrlFonte;
			}
			set
			{
				if ((this._UrlFonte != value))
				{
					this.OnUrlFonteChanging(value);
					this.SendPropertyChanging();
					this._UrlFonte = value;
					this.SendPropertyChanged("UrlFonte");
					this.OnUrlFonteChanged();
				}
			}
		}
		
		[Column(Storage="_DescrioneFonte", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[DataMember(Order=7)]
		public string DescrioneFonte
		{
			get
			{
				return this._DescrioneFonte;
			}
			set
			{
				if ((this._DescrioneFonte != value))
				{
					this.OnDescrioneFonteChanging(value);
					this.SendPropertyChanging();
					this._DescrioneFonte = value;
					this.SendPropertyChanged("DescrioneFonte");
					this.OnDescrioneFonteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.Categorie")]
	[DataContract()]
	public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DescrizioneCategoria;
		
		private string _DescrizioneBreve;
		
		private System.Nullable<int> _IDCategoriaPadre;
		
		private string _UrlImmagine;
		
		private string _DescrizioneEstesa;
		
		private string _Keywords;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDescrizioneCategoriaChanging(string value);
    partial void OnDescrizioneCategoriaChanged();
    partial void OnDescrizioneBreveChanging(string value);
    partial void OnDescrizioneBreveChanged();
    partial void OnIDCategoriaPadreChanging(System.Nullable<int> value);
    partial void OnIDCategoriaPadreChanged();
    partial void OnUrlImmagineChanging(string value);
    partial void OnUrlImmagineChanged();
    partial void OnDescrizioneEstesaChanging(string value);
    partial void OnDescrizioneEstesaChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    #endregion
		
		public Categorie()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_DescrizioneCategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		[DataMember(Order=2)]
		public string DescrizioneCategoria
		{
			get
			{
				return this._DescrizioneCategoria;
			}
			set
			{
				if ((this._DescrizioneCategoria != value))
				{
					this.OnDescrizioneCategoriaChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneCategoria = value;
					this.SendPropertyChanged("DescrizioneCategoria");
					this.OnDescrizioneCategoriaChanged();
				}
			}
		}
		
		[Column(Storage="_DescrizioneBreve", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[DataMember(Order=3)]
		public string DescrizioneBreve
		{
			get
			{
				return this._DescrizioneBreve;
			}
			set
			{
				if ((this._DescrizioneBreve != value))
				{
					this.OnDescrizioneBreveChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneBreve = value;
					this.SendPropertyChanged("DescrizioneBreve");
					this.OnDescrizioneBreveChanged();
				}
			}
		}
		
		[Column(Storage="_IDCategoriaPadre", DbType="Int")]
		[DataMember(Order=4)]
		public System.Nullable<int> IDCategoriaPadre
		{
			get
			{
				return this._IDCategoriaPadre;
			}
			set
			{
				if ((this._IDCategoriaPadre != value))
				{
					this.OnIDCategoriaPadreChanging(value);
					this.SendPropertyChanging();
					this._IDCategoriaPadre = value;
					this.SendPropertyChanged("IDCategoriaPadre");
					this.OnIDCategoriaPadreChanged();
				}
			}
		}
		
		[Column(Storage="_UrlImmagine", DbType="VarChar(100)")]
		[DataMember(Order=5)]
		public string UrlImmagine
		{
			get
			{
				return this._UrlImmagine;
			}
			set
			{
				if ((this._UrlImmagine != value))
				{
					this.OnUrlImmagineChanging(value);
					this.SendPropertyChanging();
					this._UrlImmagine = value;
					this.SendPropertyChanged("UrlImmagine");
					this.OnUrlImmagineChanged();
				}
			}
		}
		
		[Column(Storage="_DescrizioneEstesa", DbType="VarChar(MAX)")]
		[DataMember(Order=6)]
		public string DescrizioneEstesa
		{
			get
			{
				return this._DescrizioneEstesa;
			}
			set
			{
				if ((this._DescrizioneEstesa != value))
				{
					this.OnDescrizioneEstesaChanging(value);
					this.SendPropertyChanging();
					this._DescrizioneEstesa = value;
					this.SendPropertyChanged("DescrizioneEstesa");
					this.OnDescrizioneEstesaChanged();
				}
			}
		}
		
		[Column(Storage="_Keywords", DbType="VarChar(150)")]
		[DataMember(Order=7)]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.Errori")]
	[DataContract()]
	public partial class Errori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DescrException;
		
		private string _DescrStackTrace;
		
		private string _PathPagina;
		
		private string _DescrInnerException;
		
		private System.Nullable<int> _CurrentIDUtenteLoggato;
		
		private System.DateTime _DataErrore;
		
		private string _Browser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDescrExceptionChanging(string value);
    partial void OnDescrExceptionChanged();
    partial void OnDescrStackTraceChanging(string value);
    partial void OnDescrStackTraceChanged();
    partial void OnPathPaginaChanging(string value);
    partial void OnPathPaginaChanged();
    partial void OnDescrInnerExceptionChanging(string value);
    partial void OnDescrInnerExceptionChanged();
    partial void OnCurrentIDUtenteLoggatoChanging(System.Nullable<int> value);
    partial void OnCurrentIDUtenteLoggatoChanged();
    partial void OnDataErroreChanging(System.DateTime value);
    partial void OnDataErroreChanged();
    partial void OnBrowserChanging(string value);
    partial void OnBrowserChanged();
    #endregion
		
		public Errori()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_DescrException", DbType="VarChar(MAX)")]
		[DataMember(Order=2)]
		public string DescrException
		{
			get
			{
				return this._DescrException;
			}
			set
			{
				if ((this._DescrException != value))
				{
					this.OnDescrExceptionChanging(value);
					this.SendPropertyChanging();
					this._DescrException = value;
					this.SendPropertyChanged("DescrException");
					this.OnDescrExceptionChanged();
				}
			}
		}
		
		[Column(Storage="_DescrStackTrace", DbType="VarChar(MAX)")]
		[DataMember(Order=3)]
		public string DescrStackTrace
		{
			get
			{
				return this._DescrStackTrace;
			}
			set
			{
				if ((this._DescrStackTrace != value))
				{
					this.OnDescrStackTraceChanging(value);
					this.SendPropertyChanging();
					this._DescrStackTrace = value;
					this.SendPropertyChanged("DescrStackTrace");
					this.OnDescrStackTraceChanged();
				}
			}
		}
		
		[Column(Storage="_PathPagina", DbType="VarChar(200)")]
		[DataMember(Order=4)]
		public string PathPagina
		{
			get
			{
				return this._PathPagina;
			}
			set
			{
				if ((this._PathPagina != value))
				{
					this.OnPathPaginaChanging(value);
					this.SendPropertyChanging();
					this._PathPagina = value;
					this.SendPropertyChanged("PathPagina");
					this.OnPathPaginaChanged();
				}
			}
		}
		
		[Column(Storage="_DescrInnerException", DbType="VarChar(MAX)")]
		[DataMember(Order=5)]
		public string DescrInnerException
		{
			get
			{
				return this._DescrInnerException;
			}
			set
			{
				if ((this._DescrInnerException != value))
				{
					this.OnDescrInnerExceptionChanging(value);
					this.SendPropertyChanging();
					this._DescrInnerException = value;
					this.SendPropertyChanged("DescrInnerException");
					this.OnDescrInnerExceptionChanged();
				}
			}
		}
		
		[Column(Storage="_CurrentIDUtenteLoggato", DbType="Int")]
		[DataMember(Order=6)]
		public System.Nullable<int> CurrentIDUtenteLoggato
		{
			get
			{
				return this._CurrentIDUtenteLoggato;
			}
			set
			{
				if ((this._CurrentIDUtenteLoggato != value))
				{
					this.OnCurrentIDUtenteLoggatoChanging(value);
					this.SendPropertyChanging();
					this._CurrentIDUtenteLoggato = value;
					this.SendPropertyChanged("CurrentIDUtenteLoggato");
					this.OnCurrentIDUtenteLoggatoChanged();
				}
			}
		}
		
		[Column(Storage="_DataErrore", DbType="DateTime NOT NULL")]
		[DataMember(Order=7)]
		public System.DateTime DataErrore
		{
			get
			{
				return this._DataErrore;
			}
			set
			{
				if ((this._DataErrore != value))
				{
					this.OnDataErroreChanging(value);
					this.SendPropertyChanging();
					this._DataErrore = value;
					this.SendPropertyChanged("DataErrore");
					this.OnDataErroreChanged();
				}
			}
		}
		
		[Column(Storage="_Browser", DbType="VarChar(20)")]
		[DataMember(Order=8)]
		public string Browser
		{
			get
			{
				return this._Browser;
			}
			set
			{
				if ((this._Browser != value))
				{
					this.OnBrowserChanging(value);
					this.SendPropertyChanging();
					this._Browser = value;
					this.SendPropertyChanged("Browser");
					this.OnBrowserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[Table(Name="dbo.Curiosita")]
	[DataContract()]
	public partial class Curiosita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Categoria;
		
		private string _DescrCuriosita;
		
		private System.DateTime _DataInserimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnDescrCuriositaChanging(string value);
    partial void OnDescrCuriositaChanged();
    partial void OnDataInserimentoChanging(System.DateTime value);
    partial void OnDataInserimentoChanged();
    #endregion
		
		public Curiosita()
		{
			this.Initialize();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[DataMember(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[DataMember(Order=2)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[Column(Storage="_DescrCuriosita", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		[DataMember(Order=3)]
		public string DescrCuriosita
		{
			get
			{
				return this._DescrCuriosita;
			}
			set
			{
				if ((this._DescrCuriosita != value))
				{
					this.OnDescrCuriositaChanging(value);
					this.SendPropertyChanging();
					this._DescrCuriosita = value;
					this.SendPropertyChanged("DescrCuriosita");
					this.OnDescrCuriositaChanged();
				}
			}
		}
		
		[Column(Storage="_DataInserimento", DbType="DateTime NOT NULL")]
		[DataMember(Order=4)]
		public System.DateTime DataInserimento
		{
			get
			{
				return this._DataInserimento;
			}
			set
			{
				if ((this._DataInserimento != value))
				{
					this.OnDataInserimentoChanging(value);
					this.SendPropertyChanging();
					this._DataInserimento = value;
					this.SendPropertyChanged("DataInserimento");
					this.OnDataInserimentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[OnDeserializing()]
		[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
