#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perbaffo.Presenter.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Perbaffo")]
	public partial class ExportProdottiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ExportProdottiDataContext() : 
				base(global::Perbaffo.Presenter.Properties.Settings.Default.PerbaffoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExportProdottiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportProdottiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportProdottiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExportProdottiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.ExportProdottiIPrezzi")]
		public ISingleResult<ExportProdottiIPrezziResult> ExportProdottiIPrezzi()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ExportProdottiIPrezziResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.ExportProdottiBuyPlaza")]
		public ISingleResult<ExportProdottiBuyPlazaResult> ExportProdottiBuyPlaza()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ExportProdottiBuyPlazaResult>)(result.ReturnValue));
		}
	}
	
	public partial class ExportProdottiIPrezziResult
	{
		
		private string _Nome;
		
		private string _url;
		
		private string _urlImage;
		
		private string _Descr;
		
		private decimal _Totale;
		
		private int _ID;
		
		private string _Categoria;
		
		private string _marca;
		
		public ExportProdottiIPrezziResult()
		{
		}
		
		[Column(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[Column(Storage="_url", DbType="VarChar(124)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[Column(Storage="_urlImage", DbType="VarChar(75)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this._urlImage = value;
				}
			}
		}
		
		[Column(Storage="_Descr", DbType="VarChar(30)")]
		public string Descr
		{
			get
			{
				return this._Descr;
			}
			set
			{
				if ((this._Descr != value))
				{
					this._Descr = value;
				}
			}
		}
		
		[Column(Storage="_Totale", DbType="Decimal(0,0) NOT NULL")]
		public decimal Totale
		{
			get
			{
				return this._Totale;
			}
			set
			{
				if ((this._Totale != value))
				{
					this._Totale = value;
				}
			}
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_Categoria", DbType="VarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[Column(Storage="_marca", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
	}
	
	public partial class ExportProdottiBuyPlazaResult
	{
		
		private string _Nome;
		
		private string _Descr;
		
		private string _marca;
		
		private decimal _Totale;
		
		private string _Categoria;
		
		private string _urlImage;
		
		private string _url;
		
		private string _STATO;
		
		public ExportProdottiBuyPlazaResult()
		{
		}
		
		[Column(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[Column(Storage="_Descr", DbType="VarChar(MAX)")]
		public string Descr
		{
			get
			{
				return this._Descr;
			}
			set
			{
				if ((this._Descr != value))
				{
					this._Descr = value;
				}
			}
		}
		
		[Column(Storage="_marca", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
		
		[Column(Storage="_Totale", DbType="Decimal(0,0) NOT NULL")]
		public decimal Totale
		{
			get
			{
				return this._Totale;
			}
			set
			{
				if ((this._Totale != value))
				{
					this._Totale = value;
				}
			}
		}
		
		[Column(Storage="_Categoria", DbType="VarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[Column(Storage="_urlImage", DbType="VarChar(75)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this._urlImage = value;
				}
			}
		}
		
		[Column(Storage="_url", DbType="VarChar(124)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[Column(Storage="_STATO", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string STATO
		{
			get
			{
				return this._STATO;
			}
			set
			{
				if ((this._STATO != value))
				{
					this._STATO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
