<?xml version="1.0" encoding="utf-8"?>
<Database Name="Perbaffo" Class="OrdiniModelDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.3\SQLEXPRESS;Initial Catalog=Perbaffo;Persist Security Info=True;User ID=Perbaffo" SettingsObjectName="Perbaffo.Presenter.Properties.Settings" SettingsPropertyName="PerbaffoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TipoPagamento" Member="TipoPagamentos">
    <Type Name="TipoPagamento">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DescrizionePagamento" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Costo" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Attivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TipoSpedizioni" Member="TipoSpedizionis">
    <Type Name="TipoSpedizioni">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescrBreveSpedizione" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DescrSpedizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CostoSpedizione" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Attivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DettagliOrdini" Member="DettagliOrdinis">
    <Type Name="DettagliOrdini">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTaglia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDColore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Totale" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StatoOrdine" Member="StatoOrdines">
    <Type Name="StatoOrdine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescrStatoOrdine" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UtentiPromozioni" Member="UtentiPromozionis">
    <Type Name="UtentiPromozioni">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUtente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScontoEuro" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="ScontoPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataScadenza" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DescrPromozione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Attiva" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MinimoOrdine" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="NumVolte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CodicePromozioni" Member="CodicePromozionis">
    <Type Name="CodicePromozioni">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodiceSconto" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ScontoEuro" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="ScontoPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataScadenza" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DescrPromozione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Attiva" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MinimoOrdine" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_OrdineDettagliato" Member="OrdiniDettagliatos">
    <Type Name="OrdiniDettagliato">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDUtente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="IDTipoPagamento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTipoSpedizione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodiceSpedizione" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TotaleOrdine" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Citta" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDStatoOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataOrdine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDProdottoOmaggio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescrizionePagamento" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescrBreveSpedizione" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DescrSpedizione" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DescrStatoOrdine" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDUtentePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotaleScontoPerbaffo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotaleScontoCodice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CodicePromozione" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IDCodicePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotePerbaffo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CodiceAffiliazione" Member="CodiceAffiliaziones">
    <Type Name="CodiceAffiliazione">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sito" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Codice" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AffiliazioneOrdini" Member="AffiliazioneOrdinis">
    <Type Name="AffiliazioneOrdini">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCodiceAffiliazione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataOrdine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Ordini" Member="Ordinis">
    <Type Name="Ordini">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUtente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTipoPagamento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTipoSpedizione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCodicePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDUtentePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodiceSpedizione" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TotaleOrdine" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Citta" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="IDStatoOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataOrdine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDProdottoOmaggio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotaleScontoPerbaffo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotaleScontoCodice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CodicePromozione" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NotePerbaffo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TotaleScontoSpedizione" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>