<?xml version="1.0" encoding="utf-8"?>
<Database Name="Perbaffo" Class="StatisticheModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.3\SQLEXPRESS;Initial Catalog=Perbaffo;Persist Security Info=True;User ID=Perbaffo" SettingsObjectName="Perbaffo.Presenter.Properties.Settings" SettingsPropertyName="PerbaffoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StatisticheProdotti" Member="StatisticheProdottis">
    <Type Name="StatisticheProdotti">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contatore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StatisticheVisite" Member="StatisticheVisites">
    <Type Name="StatisticheVisite">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contatore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataStatistica" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StatisticheTecniche" Member="StatisticheTecniches">
    <Type Name="StatisticheTecniche">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescrBrowser" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RSSFeed" Member="RSSFeeds">
    <Type Name="RSSFeed">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titolo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Contenuto" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UrlDettaglio" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DataCreazione" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Ordini" Member="OrdiniStatistiches">
    <Type Name="OrdiniStatistiche">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUtente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTipoPagamento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTipoSpedizione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCodicePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDUtentePromozione" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodiceSpedizione" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TotaleOrdine" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Citta" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="IDStatoOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataOrdine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDProdottoOmaggio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotaleScontoPerbaffo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotaleScontoCodice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CodicePromozione" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NotePerbaffo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TotaleScontoSpedizione" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Utenti" Member="UtentiStatistiches">
    <Type Name="UtentiStatistiche">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CFiscPIva" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Citta" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RagioneSociale" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CAP" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NumeroCivico" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NotePerbaffo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DataCreazioneUtente" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataLastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterGatti" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterCani" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterVolatili" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterRoditori" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterRettili" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetterAcquarologia" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAttivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImgFriend" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NomeFriend" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prodotti" Member="ProdottiStatistiches">
    <Type Name="ProdottiStatistiche">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codice" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Keywords" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DescrizioneLunga" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Prezzo" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="DescrTaglia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDAliquotaIva" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitaDiMisura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Giacenza" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LivRiordino" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScontoPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScontoEuro" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Totale" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsOmaggio" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RangeOmaggio" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Attivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DettagliOrdini" Member="DettagliOrdiniStatistiches">
    <Type Name="DettagliOrdiniStatistiche">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDOrdine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDProdotto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTaglia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDColore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Totale" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>