//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perbaffo.Web.UI {
    
    
    public partial class Dettaglio_Ordini_Effettuati {
        
        /// <summary>
        /// frmPerbaffoPetShop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmPerbaffoPetShop;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// Header1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.Header Header1;
        
        /// <summary>
        /// MenuPerbaffo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.MenuCategorie MenuPerbaffo;
        
        /// <summary>
        /// updPnlOrdini control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updPnlOrdini;
        
        /// <summary>
        /// lblDescrDettaglio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDescrDettaglio;
        
        /// <summary>
        /// rptDettaglio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptDettaglio;
        
        /// <summary>
        /// divOrdiniAttivi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOrdiniAttivi;
        
        /// <summary>
        /// rptOrdiniAttivi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptOrdiniAttivi;
        
        /// <summary>
        /// divOrdiniStorico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divOrdiniStorico;
        
        /// <summary>
        /// rptOrdiniStorico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptOrdiniStorico;
        
        /// <summary>
        /// regist control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetRegistrazione regist;
        
        /// <summary>
        /// WidgetNewsletter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetNewsletter WidgetNewsletter;
        
        /// <summary>
        /// WidgetFoto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetFoto WidgetFoto;
        
        /// <summary>
        /// usrCarrello control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetCarrello usrCarrello;
        
        /// <summary>
        /// WidgetAssistenza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetAssistenza WidgetAssistenza;
        
        /// <summary>
        /// WidgetPerbaffo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetPerbaffo WidgetPerbaffo;
        
        /// <summary>
        /// WidgetPerbaffoWorld control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetPerbaffoWorld WidgetPerbaffoWorld;
        
        /// <summary>
        /// Notizie control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.WidgetNews Notizie;
        
        /// <summary>
        /// FooterPerbaffo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Perbaffo.Web.UI.Footer FooterPerbaffo;
    }
}
